"""Tests for the canonical schema-doc generator.

Ensures ``docs/schemas/{signals,annotations,manifests}.md`` stays in sync
with the authoritative code sources:

- ``signals`` → :class:`agent_diagnostics.types.TrialSignals` TypedDict
- ``annotations`` → :data:`agent_diagnostics.annotation_store.ROW_FIELDS`
- ``manifests`` → keys emitted by
  :func:`agent_diagnostics.export.refresh_manifests`

The drift test regenerates the docs into a temp directory and diffs the
result against the checked-in files. If a contributor adds a column
without regenerating, this test fails with a pointer to the regen
command.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_DIR = REPO_ROOT / "docs" / "schemas"
GENERATOR_PATH = REPO_ROOT / "scripts" / "gen_schema_docs.py"

TABLE_NAMES = ("signals", "annotations", "manifests")


@pytest.fixture(scope="session")
def generator_module() -> ModuleType:
    """Dynamically import scripts/gen_schema_docs.py once per test session.

    Session-scoped so the script is loaded and its module-level dataclasses
    constructed exactly once — otherwise the 7 tests below would each
    re-exec the file.

    The module is registered in ``sys.modules`` **before** ``exec_module``
    because ``@dataclass(frozen=True)`` (used for ``_Column``) looks up
    ``cls.__module__`` via ``sys.modules`` during class construction. If
    the module is not addressable under its spec name at that point, the
    decorator raises.

    Raises RuntimeError (not ``assert``) on loader failure so the guard
    still protects callers when tests run under ``python -O``.
    """
    spec = importlib.util.spec_from_file_location(
        "gen_schema_docs_test_module", GENERATOR_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(
            f"Could not load import spec for {GENERATOR_PATH}; "
            "check the file exists and is a regular Python module."
        )
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Generator structure — per-table column coverage
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("table", TABLE_NAMES)
def test_generated_doc_contains_markdown_column_table(
    table: str, generator_module: ModuleType
) -> None:
    """Every table doc must contain a Markdown column table with a header."""
    rendered = generator_module.render_table_doc(table)

    assert rendered.startswith("<!-- AUTOGENERATED"), (
        "Generated doc must begin with an autogenerated banner pointing to the "
        "source file and regen command."
    )
    assert "| Column |" in rendered, "Expected a Markdown column header row"
    assert "| Type |" in rendered, "Expected a Markdown type header row"


def test_signals_doc_covers_every_trial_signals_field(
    generator_module: ModuleType,
) -> None:
    """Every field in TrialSignals must appear in the signals doc.

    Uses ``typing.get_type_hints`` (not ``__annotations__``) so this test
    matches what the generator actually consumes and so TYPE_CHECKING-only
    forward references surface as NameError here rather than silently
    passing a check that the generator would fail.
    """
    import typing

    from agent_diagnostics.types import TrialSignals

    rendered = generator_module.render_table_doc("signals")

    expected = set(typing.get_type_hints(TrialSignals).keys())
    for field in expected:
        assert f"| {field} |" in rendered, (
            f"TrialSignals field {field!r} missing from signals.md "
            f"— regenerate docs/schemas/ from code."
        )


def test_annotations_doc_covers_every_row_field(generator_module: ModuleType) -> None:
    """Every AnnotationStore.ROW_FIELDS entry must appear in annotations.md."""
    from agent_diagnostics.annotation_store import ROW_FIELDS

    rendered = generator_module.render_table_doc("annotations")

    for field in ROW_FIELDS:
        assert f"| {field} |" in rendered, (
            f"AnnotationStore field {field!r} missing from annotations.md"
        )


def test_manifests_doc_covers_every_refresh_manifests_key(
    generator_module: ModuleType,
) -> None:
    """Every key in ``_MANIFESTS_DESCRIPTIONS`` must appear in manifests.md.

    Sources the expected key set from the generator's own
    ``_MANIFESTS_DESCRIPTIONS`` rather than a hardcoded tuple. Otherwise
    if ``export.refresh_manifests`` gains a key that the generator's
    descriptions table forgets, a hardcoded list here would silently keep
    passing while the docs drifted out of sync with the producer.
    """
    rendered = generator_module.render_table_doc("manifests")

    for field in generator_module._MANIFESTS_DESCRIPTIONS:
        assert f"| {field} |" in rendered, (
            f"manifests field {field!r} missing from manifests.md"
        )


# ---------------------------------------------------------------------------
# Drift check — committed docs must match the generator output
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("table", TABLE_NAMES)
def test_checked_in_doc_matches_generator_output(
    table: str, generator_module: ModuleType
) -> None:
    """The committed ``docs/schemas/<table>.md`` must match the generator.

    If this fails, run::

        python scripts/gen_schema_docs.py

    to refresh the docs and commit the result.
    """
    expected = generator_module.render_table_doc(table)

    doc_path = SCHEMAS_DIR / f"{table}.md"
    assert doc_path.is_file(), (
        f"Missing canonical schema doc: {doc_path}. "
        "Run `python scripts/gen_schema_docs.py` to create it."
    )
    actual = doc_path.read_text(encoding="utf-8")

    assert actual == expected, (
        f"docs/schemas/{table}.md is out of sync with code. "
        "Run `python scripts/gen_schema_docs.py` to refresh."
    )


def test_generator_writes_all_three_tables(
    tmp_path: Path, generator_module: ModuleType
) -> None:
    """Running the generator end-to-end writes all three table docs."""
    generator_module.write_all_schema_docs(tmp_path)

    for table in TABLE_NAMES:
        path = tmp_path / f"{table}.md"
        assert path.is_file(), f"Generator failed to write {path}"
        content = path.read_text(encoding="utf-8")
        assert content.startswith("<!-- AUTOGENERATED")
