"""Tests for the canonical schema-doc generator.

Ensures ``docs/schemas/{signals,annotations,manifests}.md`` stays in sync
with the authoritative code sources:

- ``signals`` → :class:`agent_diagnostics.types.TrialSignals` TypedDict
- ``annotations`` → :data:`agent_diagnostics.annotation_store.ROW_FIELDS`
- ``manifests`` → keys emitted by
  :func:`agent_diagnostics.export.refresh_manifests`

The drift test regenerates the docs into a temp directory and diffs the
result against the checked-in files. If a contributor adds a column
without regenerating, this test fails with a pointer to the regen
command.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_DIR = REPO_ROOT / "docs" / "schemas"
GENERATOR_PATH = REPO_ROOT / "scripts" / "gen_schema_docs.py"

TABLE_NAMES = ("signals", "annotations", "manifests")


def _load_generator_module():
    """Dynamically import scripts/gen_schema_docs.py so tests don't need
    a package-ified scripts directory.
    """
    spec = importlib.util.spec_from_file_location("gen_schema_docs_test_module", GENERATOR_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # Register under a unique name to avoid polluting sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Generator structure — per-table column coverage
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("table", TABLE_NAMES)
def test_generated_doc_contains_markdown_column_table(table: str) -> None:
    """Every table doc must contain a Markdown column table with a header."""
    gen = _load_generator_module()
    rendered = gen.render_table_doc(table)

    assert rendered.startswith("<!-- AUTOGENERATED"), (
        "Generated doc must begin with an autogenerated banner pointing to the "
        "source file and regen command."
    )
    assert "| Column |" in rendered, "Expected a Markdown column header row"
    assert "| Type |" in rendered, "Expected a Markdown type header row"


def test_signals_doc_covers_every_trial_signals_field() -> None:
    """Every field in TrialSignals must appear in the signals doc."""
    from agent_diagnostics.types import TrialSignals

    gen = _load_generator_module()
    rendered = gen.render_table_doc("signals")

    expected = set(TrialSignals.__annotations__.keys())
    for field in expected:
        assert f"| {field} |" in rendered, (
            f"TrialSignals field {field!r} missing from signals.md "
            f"— regenerate docs/schemas/ from code."
        )


def test_annotations_doc_covers_every_row_field() -> None:
    """Every AnnotationStore.ROW_FIELDS entry must appear in annotations.md."""
    from agent_diagnostics.annotation_store import ROW_FIELDS

    gen = _load_generator_module()
    rendered = gen.render_table_doc("annotations")

    for field in ROW_FIELDS:
        assert f"| {field} |" in rendered, (
            f"AnnotationStore field {field!r} missing from annotations.md"
        )


def test_manifests_doc_covers_every_refresh_manifests_key() -> None:
    """Every key written by refresh_manifests() must appear in manifests.md."""
    gen = _load_generator_module()
    rendered = gen.render_table_doc("manifests")

    # Keys written by export.refresh_manifests
    for field in ("manifest_id", "benchmark", "task_count", "created_at"):
        assert f"| {field} |" in rendered, f"manifests field {field!r} missing from manifests.md"


# ---------------------------------------------------------------------------
# Drift check — committed docs must match the generator output
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("table", TABLE_NAMES)
def test_checked_in_doc_matches_generator_output(table: str) -> None:
    """The committed ``docs/schemas/<table>.md`` must match the generator.

    If this fails, run::

        python scripts/gen_schema_docs.py

    to refresh the docs and commit the result.
    """
    gen = _load_generator_module()
    expected = gen.render_table_doc(table)

    doc_path = SCHEMAS_DIR / f"{table}.md"
    assert doc_path.is_file(), (
        f"Missing canonical schema doc: {doc_path}. "
        "Run `python scripts/gen_schema_docs.py` to create it."
    )
    actual = doc_path.read_text(encoding="utf-8")

    assert actual == expected, (
        f"docs/schemas/{table}.md is out of sync with code. "
        "Run `python scripts/gen_schema_docs.py` to refresh."
    )


def test_generator_writes_all_three_tables(tmp_path: Path) -> None:
    """Running the generator end-to-end writes all three table docs."""
    gen = _load_generator_module()
    gen.write_all_schema_docs(tmp_path)

    for table in TABLE_NAMES:
        path = tmp_path / f"{table}.md"
        assert path.is_file(), f"Generator failed to write {path}"
        content = path.read_text(encoding="utf-8")
        assert content.startswith("<!-- AUTOGENERATED")
